apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmdemo2
spec:
  selector:
    matchLabels:
      app: cmdemo2
  replicas: 1
  template:
    metadata:
      labels:
        app: cmdemo2
    spec:
      containers:
        - name: cmdemo2
          image: alpine
          imagePullPolicy: IfNotPresent #永远拉最新的镜像。
          command: ["/bin/sh","-c","env;sleep 3600"]
          volumeMounts:
            - mountPath: /usr/local/mysql/conf #挂载到容器的目录。
              name: db-config #valumes中对应的名称。
              readOnly: true
      volumes:
        - name: db-config
          configMap:
            name: my.cm2.cnf #configmap的名称。
            items:
              - key:  my.cm2.cnf #configmap中key的名称。 k create cm my.cm2.cnf --from-file=my.cm2.cnf
                path: my.cm2.cnf #挂载后key重名名后的名字。