// Code generated by goctl. DO NOT EDIT.
package types

type Base struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type LoginReq struct {
	Name string `form:"name"`         // 必填参数
	Age  int    `form:"age,optional"` // optional定义非必填参数
}

type LoginReplyData struct {
	Id           int64  `json:"id"`
	Name         string `json:"name"`
	Gender       string `json:"gender"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type LoginReply struct {
	Base
	Data LoginReplyData `json:"data"`
}
