// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTdOrderExec = "td_order_exec"

// TdOrderExec mapped from table <td_order_exec>
type TdOrderExec struct {
	ID                  int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增id" json:"id"`
	CreatedAt           int64   `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`
	UpdatedAt           int64   `gorm:"column:updated_at;not null;comment:更新时间" json:"updated_at"`
	SeatNo              string  `gorm:"column:seat_no;not null;comment:席位编号 IB111" json:"seat_no"`
	ReportNo            *string `gorm:"column:report_no;comment:申报编号" json:"report_no"`
	ReportTime          int64   `gorm:"column:report_time;not null;comment:申报时间,UTC 单位(秒)" json:"report_time"`
	ReportAccount       string  `gorm:"column:report_account;not null;comment:报盘机申报子账号" json:"report_account"`
	OrderInstructType   int64   `gorm:"column:order_instruct_type;not null;comment:报盘指令类型,1=新订单报盘指令(New Order),2=改单盘指令(Order Replace),3=撤单盘指令(Order Cancel)" json:"order_instruct_type"`
	OrderInstructStatus int64   `gorm:"column:order_instruct_status;not null;comment:报盘指令执行状态,0=待审核(Pending Review),1=未执行(No Execute),2=待执行(Pending Execute),3=执行中(Executing),4=执行完毕(Executed)" json:"order_instruct_status"`
	OrgID               string  `gorm:"column:org_id;not null;default:' ';comment:机构编号" json:"org_id"`
	ClientID            string  `gorm:"column:client_id;not null;comment:客户编号 1090000320" json:"client_id"`
	FundAccount         string  `gorm:"column:fund_account;not null;comment:资产账户 109000032001" json:"fund_account"`
	TradeDate           int64   `gorm:"column:trade_date;not null;comment:交易日期 20220228" json:"trade_date"`
	OrderTxnReference   string  `gorm:"column:order_txn_reference;not null;comment:记录号 2022022800US0000000001" json:"order_txn_reference"`
	ExchangeType        string  `gorm:"column:exchange_type;not null;comment:交易所类别 HK/US" json:"exchange_type"`
	MoneyType           string  `gorm:"column:money_type;not null;comment:币种类别" json:"money_type"`
	StockCode           string  `gorm:"column:stock_code;not null;comment:证券代码" json:"stock_code"`
	StockType           string  `gorm:"column:stock_type;not null;comment:证券类别 [AC_STOCK_TYPE]0:Stock 1:Fund D:WRNT F:BWRT U:BOND i:Inline Warrant" json:"stock_type"`
	EntrustBs           int64   `gorm:"column:entrust_bs;not null;comment:买卖方向 1=买(Buy),2=卖(Sell)" json:"entrust_bs"`
	EntrustProp         string  `gorm:"column:entrust_prop;not null;comment:委托属性 [TD_ORDER_PROPERTIES]ALO:At-auction Limit Order  AO:At-auction Order  ASO:Auto Stage Order  BC:Bulk Cancel  ELO:Enhanced Limit Order  LO:Limit Order  M:Manual Trade  MO:Market Order  O:Odd Lot Trade  OBC:OBO Bulk Cancel  ODD:Odd Lot Input  P:Pre Opening Trade  SLO:Special Limit Order  SODD:Special Odd Lot Order  V:Overseas Trade" json:"entrust_prop"`
	EntrustAmount       float64 `gorm:"column:entrust_amount;not null;comment:委托数量" json:"entrust_amount"`
	EntrustPrice        float64 `gorm:"column:entrust_price;not null;comment:委托价格" json:"entrust_price"`
	EntrustBalance      float64 `gorm:"column:entrust_balance;not null;comment:委托金额" json:"entrust_balance"`
	FrozenPrice         float64 `gorm:"column:frozen_price;not null;comment:已冻结价格" json:"frozen_price"`
	FrozenAmount        float64 `gorm:"column:frozen_amount;not null;comment:已冻结数量" json:"frozen_amount"`
	FrozenBalance       float64 `gorm:"column:frozen_balance;not null;comment:已冻结金额" json:"frozen_balance"`
	NewEntrustAmount    float64 `gorm:"column:new_entrust_amount;not null;comment:新委托数量/改单数量" json:"new_entrust_amount"`
	NewEntrustPrice     float64 `gorm:"column:new_entrust_price;not null;comment:新委托价格/改单价格" json:"new_entrust_price"`
	DeltaAmount         float64 `gorm:"column:delta_amount;not null;comment:追加数量" json:"delta_amount"`
	DeltaBalance        float64 `gorm:"column:delta_balance;not null;comment:追加价格" json:"delta_balance"`
	RegisterAmount      float64 `gorm:"column:register_amount;not null;comment:登记股数/剩余挂单数量" json:"register_amount"`
	WithdrawAmount      float64 `gorm:"column:withdraw_amount;not null;comment:撤单数量,撤成数量" json:"withdraw_amount"`
	FilledAmount        float64 `gorm:"column:filled_amount;not null;comment:已成交数量" json:"filled_amount"`
	FilledBalance       float64 `gorm:"column:filled_balance;not null;comment:已成交金额" json:"filled_balance"`
	ExecNo              int64   `gorm:"column:exec_no;not null;comment:执行回报编号" json:"exec_no"`
	ExecType            int64   `gorm:"column:exec_type;not null;comment:执行回报类型 1=下单已报执行回报(OrderAccepted)，2=下单拒绝执行回报(OrderRejected)，3=成交执行回报(Filled)，4=改单成功执行回报(OrderReplaced)，5=撤单成功执行回报(OrderCancelled)，6=改单/撤单拒绝执行回报(CancelReject)" json:"exec_type"`
	ExecTime            int64   `gorm:"column:exec_time;not null;comment:执行回报时间,UTC 单位(秒)" json:"exec_time"`
	OrigClordID         string  `gorm:"column:orig_clord_id;not null;comment:原始客户订单号 -- tag41组成因子" json:"orig_clord_id"`
	ClordID             string  `gorm:"column:clord_id;not null;comment:客户订单号" json:"clord_id"`
	F11Clordid          string  `gorm:"column:f11_clordid;not null;comment:报盘订单ID" json:"f11_clordid"`
	F14Cumqty           float64 `gorm:"column:f14_cumqty;not null;comment:累计成交数量" json:"f14_cumqty"`
	F39Ordstatus        int64   `gorm:"column:f39_ordstatus;not null;comment:订单状态 1 = New，2=Rejected，3=Partially Filled，4=Filled，5=Cancelled" json:"f39_ordstatus"`
	F150Exectype        string  `gorm:"column:f150_exectype;not null;comment:执行类型" json:"f150_exectype"`
	F151Leavesqty       float64 `gorm:"column:f151_leavesqty;not null;comment:剩余数量" json:"f151_leavesqty"`
	ErrorType           string  `gorm:"column:error_type;not null;comment:错误类型 a=交易前置错误 b=柜台内部错误 s=报盘机返回错误 e=交易所返回错误" json:"error_type"`
	ErrorNo             int64   `gorm:"column:error_no;not null;comment:错误代码" json:"error_no"`
	ErrorMsg            string  `gorm:"column:error_msg;not null;comment:错误提示" json:"error_msg"`
}

// TableName TdOrderExec's table name
func (*TdOrderExec) TableName() string {
	return TableNameTdOrderExec
}
