// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: grpcdemo/grpcdemo.proto

//当别人导入这个protobuf文件，使用的包名 如 google/protobuf/empty.proto 定义的就是 package google.protobuf,我们要使用这个文件中message 使用方法为 package.Message
//如google.protobuf.Empty

package grpcdemo

import (
	folder "go-lib/net/grpc/pb/grpcdemo/folder"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 枚举类
type Gender int32

const (
	Gender_Unknown Gender = 0
	Gender_Male    Gender = 1
	Gender_Female  Gender = 2
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "Unknown",
		1: "Male",
		2: "Female",
	}
	Gender_value = map[string]int32{
		"Unknown": 0,
		"Male":    1,
		"Female":  2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_grpcdemo_grpcdemo_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_grpcdemo_grpcdemo_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_grpcdemo_grpcdemo_proto_rawDescGZIP(), []int{0}
}

type UnaryCallResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *UnaryCallResp) Reset() {
	*x = UnaryCallResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcdemo_grpcdemo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnaryCallResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryCallResp) ProtoMessage() {}

func (x *UnaryCallResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpcdemo_grpcdemo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryCallResp.ProtoReflect.Descriptor instead.
func (*UnaryCallResp) Descriptor() ([]byte, []int) {
	return file_grpcdemo_grpcdemo_proto_rawDescGZIP(), []int{0}
}

func (x *UnaryCallResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type PushDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Foo string `protobuf:"bytes,1,opt,name=foo,proto3" json:"foo,omitempty"`
}

func (x *PushDataReq) Reset() {
	*x = PushDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcdemo_grpcdemo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushDataReq) ProtoMessage() {}

func (x *PushDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpcdemo_grpcdemo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushDataReq.ProtoReflect.Descriptor instead.
func (*PushDataReq) Descriptor() ([]byte, []int) {
	return file_grpcdemo_grpcdemo_proto_rawDescGZIP(), []int{1}
}

func (x *PushDataReq) GetFoo() string {
	if x != nil {
		return x.Foo
	}
	return ""
}

type PushDataResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Foo string `protobuf:"bytes,1,opt,name=foo,proto3" json:"foo,omitempty"`
}

func (x *PushDataResp) Reset() {
	*x = PushDataResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcdemo_grpcdemo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushDataResp) ProtoMessage() {}

func (x *PushDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpcdemo_grpcdemo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushDataResp.ProtoReflect.Descriptor instead.
func (*PushDataResp) Descriptor() ([]byte, []int) {
	return file_grpcdemo_grpcdemo_proto_rawDescGZIP(), []int{2}
}

func (x *PushDataResp) GetFoo() string {
	if x != nil {
		return x.Foo
	}
	return ""
}

type ExchangeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName string  `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	Age       *string `protobuf:"bytes,2,opt,name=age,proto3,oneof" json:"age,omitempty"`
}

func (x *ExchangeReq) Reset() {
	*x = ExchangeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcdemo_grpcdemo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExchangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeReq) ProtoMessage() {}

func (x *ExchangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpcdemo_grpcdemo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeReq.ProtoReflect.Descriptor instead.
func (*ExchangeReq) Descriptor() ([]byte, []int) {
	return file_grpcdemo_grpcdemo_proto_rawDescGZIP(), []int{3}
}

func (x *ExchangeReq) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ExchangeReq) GetAge() string {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return ""
}

type ExchangeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastName string `protobuf:"bytes,1,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Gender   Gender `protobuf:"varint,2,opt,name=gender,proto3,enum=grpcdemo.Gender" json:"gender,omitempty"`
}

func (x *ExchangeResp) Reset() {
	*x = ExchangeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcdemo_grpcdemo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExchangeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeResp) ProtoMessage() {}

func (x *ExchangeResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpcdemo_grpcdemo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeResp.ProtoReflect.Descriptor instead.
func (*ExchangeResp) Descriptor() ([]byte, []int) {
	return file_grpcdemo_grpcdemo_proto_rawDescGZIP(), []int{4}
}

func (x *ExchangeResp) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ExchangeResp) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_Unknown
}

// map类型
type CallGrpcGatewayReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config map[string]string `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *CallGrpcGatewayReq) Reset() {
	*x = CallGrpcGatewayReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcdemo_grpcdemo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallGrpcGatewayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallGrpcGatewayReq) ProtoMessage() {}

func (x *CallGrpcGatewayReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpcdemo_grpcdemo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallGrpcGatewayReq.ProtoReflect.Descriptor instead.
func (*CallGrpcGatewayReq) Descriptor() ([]byte, []int) {
	return file_grpcdemo_grpcdemo_proto_rawDescGZIP(), []int{5}
}

func (x *CallGrpcGatewayReq) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type CallGrpcGatewayResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config map[string]string `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *CallGrpcGatewayResp) Reset() {
	*x = CallGrpcGatewayResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcdemo_grpcdemo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallGrpcGatewayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallGrpcGatewayResp) ProtoMessage() {}

func (x *CallGrpcGatewayResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpcdemo_grpcdemo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallGrpcGatewayResp.ProtoReflect.Descriptor instead.
func (*CallGrpcGatewayResp) Descriptor() ([]byte, []int) {
	return file_grpcdemo_grpcdemo_proto_rawDescGZIP(), []int{6}
}

func (x *CallGrpcGatewayResp) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

// protobuf oneof的用法。
type FetchDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	// Types that are assignable to NoticeWay:
	//
	//	*FetchDataReq_Email
	//	*FetchDataReq_Phone
	NoticeWay isFetchDataReq_NoticeWay `protobuf_oneof:"notice_way"`
}

func (x *FetchDataReq) Reset() {
	*x = FetchDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcdemo_grpcdemo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchDataReq) ProtoMessage() {}

func (x *FetchDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpcdemo_grpcdemo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchDataReq.ProtoReflect.Descriptor instead.
func (*FetchDataReq) Descriptor() ([]byte, []int) {
	return file_grpcdemo_grpcdemo_proto_rawDescGZIP(), []int{7}
}

func (x *FetchDataReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (m *FetchDataReq) GetNoticeWay() isFetchDataReq_NoticeWay {
	if m != nil {
		return m.NoticeWay
	}
	return nil
}

func (x *FetchDataReq) GetEmail() string {
	if x, ok := x.GetNoticeWay().(*FetchDataReq_Email); ok {
		return x.Email
	}
	return ""
}

func (x *FetchDataReq) GetPhone() string {
	if x, ok := x.GetNoticeWay().(*FetchDataReq_Phone); ok {
		return x.Phone
	}
	return ""
}

type isFetchDataReq_NoticeWay interface {
	isFetchDataReq_NoticeWay()
}

type FetchDataReq_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

type FetchDataReq_Phone struct {
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3,oneof"`
}

func (*FetchDataReq_Email) isFetchDataReq_NoticeWay() {}

func (*FetchDataReq_Phone) isFetchDataReq_NoticeWay() {}

type FetchDataResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FavBook string `protobuf:"bytes,4,opt,name=fav_book,json=favBook,proto3" json:"fav_book,omitempty"` //最爱的书
}

func (x *FetchDataResp) Reset() {
	*x = FetchDataResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcdemo_grpcdemo_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchDataResp) ProtoMessage() {}

func (x *FetchDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpcdemo_grpcdemo_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchDataResp.ProtoReflect.Descriptor instead.
func (*FetchDataResp) Descriptor() ([]byte, []int) {
	return file_grpcdemo_grpcdemo_proto_rawDescGZIP(), []int{8}
}

func (x *FetchDataResp) GetFavBook() string {
	if x != nil {
		return x.FavBook
	}
	return ""
}

type CallGrpcGatewayDemoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *CallGrpcGatewayDemoReq) Reset() {
	*x = CallGrpcGatewayDemoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcdemo_grpcdemo_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallGrpcGatewayDemoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallGrpcGatewayDemoReq) ProtoMessage() {}

func (x *CallGrpcGatewayDemoReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpcdemo_grpcdemo_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallGrpcGatewayDemoReq.ProtoReflect.Descriptor instead.
func (*CallGrpcGatewayDemoReq) Descriptor() ([]byte, []int) {
	return file_grpcdemo_grpcdemo_proto_rawDescGZIP(), []int{9}
}

func (x *CallGrpcGatewayDemoReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CallGrpcGatewayDemoReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CallGrpcGatewayDemoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *CallGrpcGatewayDemoResp) Reset() {
	*x = CallGrpcGatewayDemoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcdemo_grpcdemo_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallGrpcGatewayDemoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallGrpcGatewayDemoResp) ProtoMessage() {}

func (x *CallGrpcGatewayDemoResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpcdemo_grpcdemo_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallGrpcGatewayDemoResp.ProtoReflect.Descriptor instead.
func (*CallGrpcGatewayDemoResp) Descriptor() ([]byte, []int) {
	return file_grpcdemo_grpcdemo_proto_rawDescGZIP(), []int{10}
}

func (x *CallGrpcGatewayDemoResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CallGrpcGatewayDemoResp) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_grpcdemo_grpcdemo_proto protoreflect.FileDescriptor

var file_grpcdemo_grpcdemo_proto_rawDesc = []byte{
	0x0a, 0x17, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x64,
	0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x67, 0x72, 0x70, 0x63, 0x64,
	0x65, 0x6d, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x66, 0x6f, 0x6c, 0x64, 0x65,
	0x72, 0x2f, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x15, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x0d, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x43, 0x61,
	0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x1f, 0x0a, 0x0b, 0x50, 0x75, 0x73, 0x68, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x6f, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x66, 0x6f, 0x6f, 0x22, 0x20, 0x0a, 0x0c, 0x50, 0x75, 0x73, 0x68, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x6f, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x66, 0x6f, 0x6f, 0x22, 0x4b, 0x0a, 0x0b, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x03, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x61,
	0x67, 0x65, 0x22, 0x55, 0x0a, 0x0c, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x28, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x91, 0x01, 0x0a, 0x12, 0x43, 0x61,
	0x6c, 0x6c, 0x47, 0x72, 0x70, 0x63, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x52, 0x65, 0x71,
	0x12, 0x40, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x28, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x43, 0x61, 0x6c, 0x6c,
	0x47, 0x72, 0x70, 0x63, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x52, 0x65, 0x71, 0x2e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x1a, 0x39, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x93, 0x01,
	0x0a, 0x13, 0x43, 0x61, 0x6c, 0x6c, 0x47, 0x72, 0x70, 0x63, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x41, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f,
	0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x47, 0x72, 0x70, 0x63, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x39, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x5e, 0x0a, 0x0c, 0x46, 0x65, 0x74, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a,
	0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x5f,
	0x77, 0x61, 0x79, 0x22, 0x2a, 0x0a, 0x0d, 0x46, 0x65, 0x74, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x61, 0x76, 0x5f, 0x62, 0x6f, 0x6f, 0x6b,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x61, 0x76, 0x42, 0x6f, 0x6f, 0x6b, 0x22,
	0x50, 0x0a, 0x16, 0x43, 0x61, 0x6c, 0x6c, 0x47, 0x72, 0x70, 0x63, 0x47, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x44, 0x65, 0x6d, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x22, 0x51, 0x0a, 0x17, 0x43, 0x61, 0x6c, 0x6c, 0x47, 0x72, 0x70, 0x63, 0x47, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x44, 0x65, 0x6d, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x2a, 0x2b, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4d,
	0x61, 0x6c, 0x65, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x65, 0x6d, 0x61, 0x6c, 0x65, 0x10,
	0x02, 0x32, 0xb2, 0x03, 0x0a, 0x08, 0x47, 0x72, 0x70, 0x63, 0x44, 0x65, 0x6d, 0x6f, 0x12, 0x3c,
	0x0a, 0x09, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x55,
	0x6e, 0x61, 0x72, 0x79, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x47, 0x0a, 0x0a,
	0x44, 0x65, 0x6d, 0x6f, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x20, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x2e, 0x49, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x17, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3b, 0x0a, 0x08, 0x50, 0x75, 0x73, 0x68, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x50, 0x75, 0x73,
	0x68, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64,
	0x65, 0x6d, 0x6f, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x28, 0x01, 0x12, 0x3e, 0x0a, 0x09, 0x46, 0x65, 0x74, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65,
	0x6d, 0x6f, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x30, 0x01, 0x12, 0x3d, 0x0a, 0x08, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x15,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f,
	0x2e, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x28, 0x01, 0x30,
	0x01, 0x12, 0x63, 0x0a, 0x0f, 0x43, 0x61, 0x6c, 0x6c, 0x47, 0x72, 0x70, 0x63, 0x47, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x12, 0x1c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e,
	0x43, 0x61, 0x6c, 0x6c, 0x47, 0x72, 0x70, 0x63, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x52,
	0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x43, 0x61,
	0x6c, 0x6c, 0x47, 0x72, 0x70, 0x63, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x13, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0d, 0x3a, 0x01, 0x2a, 0x22, 0x08, 0x2f, 0x76,
	0x31, 0x2f, 0x63, 0x61, 0x6c, 0x6c, 0x32, 0x85, 0x01, 0x0a, 0x0f, 0x47, 0x72, 0x70, 0x63, 0x47,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x44, 0x65, 0x6d, 0x6f, 0x12, 0x72, 0x0a, 0x13, 0x43, 0x61,
	0x6c, 0x6c, 0x47, 0x72, 0x70, 0x63, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x44, 0x65, 0x6d,
	0x6f, 0x12, 0x20, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x43, 0x61, 0x6c,
	0x6c, 0x47, 0x72, 0x70, 0x63, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x44, 0x65, 0x6d, 0x6f,
	0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x43,
	0x61, 0x6c, 0x6c, 0x47, 0x72, 0x70, 0x63, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x44, 0x65,
	0x6d, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x3a, 0x01,
	0x2a, 0x22, 0x0b, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x42, 0x15,
	0x5a, 0x13, 0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x3b, 0x67, 0x72, 0x70,
	0x63, 0x64, 0x65, 0x6d, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpcdemo_grpcdemo_proto_rawDescOnce sync.Once
	file_grpcdemo_grpcdemo_proto_rawDescData = file_grpcdemo_grpcdemo_proto_rawDesc
)

func file_grpcdemo_grpcdemo_proto_rawDescGZIP() []byte {
	file_grpcdemo_grpcdemo_proto_rawDescOnce.Do(func() {
		file_grpcdemo_grpcdemo_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcdemo_grpcdemo_proto_rawDescData)
	})
	return file_grpcdemo_grpcdemo_proto_rawDescData
}

var file_grpcdemo_grpcdemo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpcdemo_grpcdemo_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_grpcdemo_grpcdemo_proto_goTypes = []interface{}{
	(Gender)(0),                     // 0: grpcdemo.Gender
	(*UnaryCallResp)(nil),           // 1: grpcdemo.UnaryCallResp
	(*PushDataReq)(nil),             // 2: grpcdemo.PushDataReq
	(*PushDataResp)(nil),            // 3: grpcdemo.PushDataResp
	(*ExchangeReq)(nil),             // 4: grpcdemo.ExchangeReq
	(*ExchangeResp)(nil),            // 5: grpcdemo.ExchangeResp
	(*CallGrpcGatewayReq)(nil),      // 6: grpcdemo.CallGrpcGatewayReq
	(*CallGrpcGatewayResp)(nil),     // 7: grpcdemo.CallGrpcGatewayResp
	(*FetchDataReq)(nil),            // 8: grpcdemo.FetchDataReq
	(*FetchDataResp)(nil),           // 9: grpcdemo.FetchDataResp
	(*CallGrpcGatewayDemoReq)(nil),  // 10: grpcdemo.CallGrpcGatewayDemoReq
	(*CallGrpcGatewayDemoResp)(nil), // 11: grpcdemo.CallGrpcGatewayDemoResp
	nil,                             // 12: grpcdemo.CallGrpcGatewayReq.ConfigEntry
	nil,                             // 13: grpcdemo.CallGrpcGatewayResp.ConfigEntry
	(*emptypb.Empty)(nil),           // 14: google.protobuf.Empty
	(*folder.ImportedMessage)(nil),  // 15: grpcdemo.folder.ImportedMessage
	(*CustomMessage)(nil),           // 16: grpcdemo.CustomMessage
}
var file_grpcdemo_grpcdemo_proto_depIdxs = []int32{
	0,  // 0: grpcdemo.ExchangeResp.gender:type_name -> grpcdemo.Gender
	12, // 1: grpcdemo.CallGrpcGatewayReq.config:type_name -> grpcdemo.CallGrpcGatewayReq.ConfigEntry
	13, // 2: grpcdemo.CallGrpcGatewayResp.config:type_name -> grpcdemo.CallGrpcGatewayResp.ConfigEntry
	14, // 3: grpcdemo.GrpcDemo.UnaryCall:input_type -> google.protobuf.Empty
	15, // 4: grpcdemo.GrpcDemo.DemoImport:input_type -> grpcdemo.folder.ImportedMessage
	2,  // 5: grpcdemo.GrpcDemo.PushData:input_type -> grpcdemo.PushDataReq
	8,  // 6: grpcdemo.GrpcDemo.FetchData:input_type -> grpcdemo.FetchDataReq
	4,  // 7: grpcdemo.GrpcDemo.Exchange:input_type -> grpcdemo.ExchangeReq
	6,  // 8: grpcdemo.GrpcDemo.CallGrpcGateway:input_type -> grpcdemo.CallGrpcGatewayReq
	10, // 9: grpcdemo.GrpcGatewayDemo.CallGrpcGatewayDemo:input_type -> grpcdemo.CallGrpcGatewayDemoReq
	1,  // 10: grpcdemo.GrpcDemo.UnaryCall:output_type -> grpcdemo.UnaryCallResp
	16, // 11: grpcdemo.GrpcDemo.DemoImport:output_type -> grpcdemo.CustomMessage
	3,  // 12: grpcdemo.GrpcDemo.PushData:output_type -> grpcdemo.PushDataResp
	9,  // 13: grpcdemo.GrpcDemo.FetchData:output_type -> grpcdemo.FetchDataResp
	5,  // 14: grpcdemo.GrpcDemo.Exchange:output_type -> grpcdemo.ExchangeResp
	7,  // 15: grpcdemo.GrpcDemo.CallGrpcGateway:output_type -> grpcdemo.CallGrpcGatewayResp
	11, // 16: grpcdemo.GrpcGatewayDemo.CallGrpcGatewayDemo:output_type -> grpcdemo.CallGrpcGatewayDemoResp
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_grpcdemo_grpcdemo_proto_init() }
func file_grpcdemo_grpcdemo_proto_init() {
	if File_grpcdemo_grpcdemo_proto != nil {
		return
	}
	file_grpcdemo_custom_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_grpcdemo_grpcdemo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnaryCallResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcdemo_grpcdemo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcdemo_grpcdemo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushDataResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcdemo_grpcdemo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExchangeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcdemo_grpcdemo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExchangeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcdemo_grpcdemo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallGrpcGatewayReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcdemo_grpcdemo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallGrpcGatewayResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcdemo_grpcdemo_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcdemo_grpcdemo_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchDataResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcdemo_grpcdemo_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallGrpcGatewayDemoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcdemo_grpcdemo_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallGrpcGatewayDemoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_grpcdemo_grpcdemo_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_grpcdemo_grpcdemo_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*FetchDataReq_Email)(nil),
		(*FetchDataReq_Phone)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcdemo_grpcdemo_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_grpcdemo_grpcdemo_proto_goTypes,
		DependencyIndexes: file_grpcdemo_grpcdemo_proto_depIdxs,
		EnumInfos:         file_grpcdemo_grpcdemo_proto_enumTypes,
		MessageInfos:      file_grpcdemo_grpcdemo_proto_msgTypes,
	}.Build()
	File_grpcdemo_grpcdemo_proto = out.File
	file_grpcdemo_grpcdemo_proto_rawDesc = nil
	file_grpcdemo_grpcdemo_proto_goTypes = nil
	file_grpcdemo_grpcdemo_proto_depIdxs = nil
}
