// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: grpcdemo/grpcdemo.proto

//当别人导入这个protobuf文件，使用的包名 如 google/protobuf/empty.proto 定义的就是 package google.protobuf,我们要使用这个文件中message 使用方法为 package.Message
//如google.protobuf.Empty

package grpcdemo

import (
	folder "go-lib/net/grpc/pb/grpcdemo/folder"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName string  `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	Age       *string `protobuf:"bytes,2,opt,name=age,proto3,oneof" json:"age,omitempty"`
}

func (x *Req) Reset() {
	*x = Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcdemo_grpcdemo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req) ProtoMessage() {}

func (x *Req) ProtoReflect() protoreflect.Message {
	mi := &file_grpcdemo_grpcdemo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req.ProtoReflect.Descriptor instead.
func (*Req) Descriptor() ([]byte, []int) {
	return file_grpcdemo_grpcdemo_proto_rawDescGZIP(), []int{0}
}

func (x *Req) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Req) GetAge() string {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return ""
}

type Resp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastName string `protobuf:"bytes,1,opt,name=lastName,proto3" json:"lastName,omitempty"`
}

func (x *Resp) Reset() {
	*x = Resp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcdemo_grpcdemo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resp) ProtoMessage() {}

func (x *Resp) ProtoReflect() protoreflect.Message {
	mi := &file_grpcdemo_grpcdemo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resp.ProtoReflect.Descriptor instead.
func (*Resp) Descriptor() ([]byte, []int) {
	return file_grpcdemo_grpcdemo_proto_rawDescGZIP(), []int{1}
}

func (x *Resp) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcdemo_grpcdemo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpcdemo_grpcdemo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpcdemo_grpcdemo_proto_rawDescGZIP(), []int{2}
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid   string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Topic string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Data  []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcdemo_grpcdemo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_grpcdemo_grpcdemo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_grpcdemo_grpcdemo_proto_rawDescGZIP(), []int{3}
}

func (x *Data) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Data) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Data) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type NoticeReaderResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FavBook string `protobuf:"bytes,4,opt,name=fav_book,json=favBook,proto3" json:"fav_book,omitempty"` //最爱的书
}

func (x *NoticeReaderResp) Reset() {
	*x = NoticeReaderResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcdemo_grpcdemo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoticeReaderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeReaderResp) ProtoMessage() {}

func (x *NoticeReaderResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpcdemo_grpcdemo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeReaderResp.ProtoReflect.Descriptor instead.
func (*NoticeReaderResp) Descriptor() ([]byte, []int) {
	return file_grpcdemo_grpcdemo_proto_rawDescGZIP(), []int{4}
}

func (x *NoticeReaderResp) GetFavBook() string {
	if x != nil {
		return x.FavBook
	}
	return ""
}

// protobuf oneof的用法。
type NoticeReaderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	// Types that are assignable to NoticeWay:
	//
	//	*NoticeReaderReq_Email
	//	*NoticeReaderReq_Phone
	NoticeWay isNoticeReaderReq_NoticeWay `protobuf_oneof:"notice_way"`
}

func (x *NoticeReaderReq) Reset() {
	*x = NoticeReaderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcdemo_grpcdemo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoticeReaderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeReaderReq) ProtoMessage() {}

func (x *NoticeReaderReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpcdemo_grpcdemo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeReaderReq.ProtoReflect.Descriptor instead.
func (*NoticeReaderReq) Descriptor() ([]byte, []int) {
	return file_grpcdemo_grpcdemo_proto_rawDescGZIP(), []int{5}
}

func (x *NoticeReaderReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (m *NoticeReaderReq) GetNoticeWay() isNoticeReaderReq_NoticeWay {
	if m != nil {
		return m.NoticeWay
	}
	return nil
}

func (x *NoticeReaderReq) GetEmail() string {
	if x, ok := x.GetNoticeWay().(*NoticeReaderReq_Email); ok {
		return x.Email
	}
	return ""
}

func (x *NoticeReaderReq) GetPhone() string {
	if x, ok := x.GetNoticeWay().(*NoticeReaderReq_Phone); ok {
		return x.Phone
	}
	return ""
}

type isNoticeReaderReq_NoticeWay interface {
	isNoticeReaderReq_NoticeWay()
}

type NoticeReaderReq_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

type NoticeReaderReq_Phone struct {
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3,oneof"`
}

func (*NoticeReaderReq_Email) isNoticeReaderReq_NoticeWay() {}

func (*NoticeReaderReq_Phone) isNoticeReaderReq_NoticeWay() {}

var File_grpcdemo_grpcdemo_proto protoreflect.FileDescriptor

var file_grpcdemo_grpcdemo_proto_rawDesc = []byte{
	0x0a, 0x17, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x64,
	0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x67, 0x72, 0x70, 0x63, 0x64,
	0x65, 0x6d, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x66, 0x6f, 0x6c, 0x64, 0x65,
	0x72, 0x2f, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x15, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09,
	0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x03, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x61, 0x67, 0x65, 0x88, 0x01,
	0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x61, 0x67, 0x65, 0x22, 0x22, 0x0a, 0x04, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x07, 0x0a,
	0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x42, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2d, 0x0a, 0x10, 0x4e, 0x6f,
	0x74, 0x69, 0x63, 0x65, 0x52, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x19,
	0x0a, 0x08, 0x66, 0x61, 0x76, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x66, 0x61, 0x76, 0x42, 0x6f, 0x6f, 0x6b, 0x22, 0x61, 0x0a, 0x0f, 0x4e, 0x6f, 0x74,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x16,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x42, 0x0c,
	0x0a, 0x0a, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x5f, 0x77, 0x61, 0x79, 0x32, 0x80, 0x03, 0x0a,
	0x08, 0x47, 0x72, 0x70, 0x63, 0x44, 0x65, 0x6d, 0x6f, 0x12, 0x3e, 0x0a, 0x09, 0x55, 0x6e, 0x61,
	0x72, 0x79, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d,
	0x6f, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x52, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x47, 0x0a, 0x0a, 0x44, 0x65, 0x6d,
	0x6f, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x20, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65,
	0x6d, 0x6f, 0x2e, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x2d, 0x0a, 0x08, 0x50, 0x75, 0x73, 0x68, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0f,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x28,
	0x01, 0x12, 0x2e, 0x0a, 0x09, 0x46, 0x65, 0x74, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0f,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x30,
	0x01, 0x12, 0x2d, 0x0a, 0x08, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x0d, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x28, 0x01, 0x30, 0x01,
	0x12, 0x5d, 0x0a, 0x0f, 0x43, 0x61, 0x6c, 0x6c, 0x47, 0x72, 0x70, 0x63, 0x47, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x4e,
	0x6f, 0x74, 0x69, 0x63, 0x65, 0x52, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1a,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x13, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x0d, 0x3a, 0x01, 0x2a, 0x22, 0x08, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x61, 0x6c, 0x6c, 0x32,
	0x77, 0x0a, 0x0f, 0x47, 0x72, 0x70, 0x63, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x44, 0x65,
	0x6d, 0x6f, 0x12, 0x64, 0x0a, 0x13, 0x43, 0x61, 0x6c, 0x6c, 0x47, 0x72, 0x70, 0x63, 0x47, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x44, 0x65, 0x6d, 0x6f, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x52, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e,
	0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x52, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x3a, 0x01, 0x2a, 0x22, 0x0b, 0x2f, 0x76, 0x31,
	0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpcdemo_grpcdemo_proto_rawDescOnce sync.Once
	file_grpcdemo_grpcdemo_proto_rawDescData = file_grpcdemo_grpcdemo_proto_rawDesc
)

func file_grpcdemo_grpcdemo_proto_rawDescGZIP() []byte {
	file_grpcdemo_grpcdemo_proto_rawDescOnce.Do(func() {
		file_grpcdemo_grpcdemo_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcdemo_grpcdemo_proto_rawDescData)
	})
	return file_grpcdemo_grpcdemo_proto_rawDescData
}

var file_grpcdemo_grpcdemo_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpcdemo_grpcdemo_proto_goTypes = []interface{}{
	(*Req)(nil),                    // 0: grpcdemo.Req
	(*Resp)(nil),                   // 1: grpcdemo.Resp
	(*Empty)(nil),                  // 2: grpcdemo.Empty
	(*Data)(nil),                   // 3: grpcdemo.Data
	(*NoticeReaderResp)(nil),       // 4: grpcdemo.NoticeReaderResp
	(*NoticeReaderReq)(nil),        // 5: grpcdemo.NoticeReaderReq
	(*folder.ImportedMessage)(nil), // 6: grpcdemo.folder.ImportedMessage
	(*emptypb.Empty)(nil),          // 7: google.protobuf.Empty
	(*CustomMessage)(nil),          // 8: grpcdemo.CustomMessage
}
var file_grpcdemo_grpcdemo_proto_depIdxs = []int32{
	5, // 0: grpcdemo.GrpcDemo.UnaryCall:input_type -> grpcdemo.NoticeReaderReq
	6, // 1: grpcdemo.GrpcDemo.DemoImport:input_type -> grpcdemo.folder.ImportedMessage
	2, // 2: grpcdemo.GrpcDemo.PushData:input_type -> grpcdemo.Empty
	2, // 3: grpcdemo.GrpcDemo.FetchData:input_type -> grpcdemo.Empty
	0, // 4: grpcdemo.GrpcDemo.Exchange:input_type -> grpcdemo.Req
	5, // 5: grpcdemo.GrpcDemo.CallGrpcGateway:input_type -> grpcdemo.NoticeReaderReq
	5, // 6: grpcdemo.GrpcGatewayDemo.CallGrpcGatewayDemo:input_type -> grpcdemo.NoticeReaderReq
	7, // 7: grpcdemo.GrpcDemo.UnaryCall:output_type -> google.protobuf.Empty
	8, // 8: grpcdemo.GrpcDemo.DemoImport:output_type -> grpcdemo.CustomMessage
	3, // 9: grpcdemo.GrpcDemo.PushData:output_type -> grpcdemo.Data
	3, // 10: grpcdemo.GrpcDemo.FetchData:output_type -> grpcdemo.Data
	1, // 11: grpcdemo.GrpcDemo.Exchange:output_type -> grpcdemo.Resp
	4, // 12: grpcdemo.GrpcDemo.CallGrpcGateway:output_type -> grpcdemo.NoticeReaderResp
	4, // 13: grpcdemo.GrpcGatewayDemo.CallGrpcGatewayDemo:output_type -> grpcdemo.NoticeReaderResp
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcdemo_grpcdemo_proto_init() }
func file_grpcdemo_grpcdemo_proto_init() {
	if File_grpcdemo_grpcdemo_proto != nil {
		return
	}
	file_grpcdemo_custom_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_grpcdemo_grpcdemo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcdemo_grpcdemo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcdemo_grpcdemo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcdemo_grpcdemo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcdemo_grpcdemo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoticeReaderResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcdemo_grpcdemo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoticeReaderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_grpcdemo_grpcdemo_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_grpcdemo_grpcdemo_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*NoticeReaderReq_Email)(nil),
		(*NoticeReaderReq_Phone)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcdemo_grpcdemo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_grpcdemo_grpcdemo_proto_goTypes,
		DependencyIndexes: file_grpcdemo_grpcdemo_proto_depIdxs,
		MessageInfos:      file_grpcdemo_grpcdemo_proto_msgTypes,
	}.Build()
	File_grpcdemo_grpcdemo_proto = out.File
	file_grpcdemo_grpcdemo_proto_rawDesc = nil
	file_grpcdemo_grpcdemo_proto_goTypes = nil
	file_grpcdemo_grpcdemo_proto_depIdxs = nil
}
