// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserName string `gorm:"column:user_name;not null" json:"user_name"`
	Age      int32  `gorm:"column:age;not null" json:"age"`
	Fav      string `gorm:"column:fav;not null" json:"fav"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
