name = 'zhangsan'

[clients]
data = [['gamma', 'delta'], [1, 2]]

[database]
connection_max = 5000
enabled = true
ports = [8001, 8001, 8002]
server = '192.168.1.1'

[file]
version = 8

[gin]
port = 10010

[owner]
bio = "Github Cofounder &amp; CEO\nLikes tater tots and beer."
dob = 1979-05-27T07:32:00Z
name = 'Tom Preston-Werner'
organization = 'Github'

[person]
age = 23
ageage = 1
fav = ['唱', '跳', 'rap', '篮球']
name = '张飒'

[servers]
[servers.alpha]
dc = 'eqdc10'
ip = '10.0.0.1'

[servers.beta]
dc = 'eqdc10'
ip = '10.0.0.2'
