// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gorm/model"
)

func newTdOrderInstruct(db *gorm.DB, opts ...gen.DOOption) tdOrderInstruct {
	_tdOrderInstruct := tdOrderInstruct{}

	_tdOrderInstruct.tdOrderInstructDo.UseDB(db, opts...)
	_tdOrderInstruct.tdOrderInstructDo.UseModel(&model.TdOrderInstruct{})

	tableName := _tdOrderInstruct.tdOrderInstructDo.TableName()
	_tdOrderInstruct.ALL = field.NewAsterisk(tableName)
	_tdOrderInstruct.ID = field.NewInt64(tableName, "id")
	_tdOrderInstruct.CreatedAt = field.NewInt64(tableName, "created_at")
	_tdOrderInstruct.UpdatedAt = field.NewInt64(tableName, "updated_at")
	_tdOrderInstruct.SeatNo = field.NewString(tableName, "seat_no")
	_tdOrderInstruct.ReportNo = field.NewString(tableName, "report_no")
	_tdOrderInstruct.ReportTime = field.NewInt64(tableName, "report_time")
	_tdOrderInstruct.ReportAccount = field.NewString(tableName, "report_account")
	_tdOrderInstruct.OrderInstructType = field.NewInt64(tableName, "order_instruct_type")
	_tdOrderInstruct.OrderInstructStatus = field.NewInt64(tableName, "order_instruct_status")
	_tdOrderInstruct.OrgID = field.NewString(tableName, "org_id")
	_tdOrderInstruct.ClientID = field.NewString(tableName, "client_id")
	_tdOrderInstruct.FundAccount = field.NewString(tableName, "fund_account")
	_tdOrderInstruct.TradeDate = field.NewInt64(tableName, "trade_date")
	_tdOrderInstruct.OrderTxnReference = field.NewString(tableName, "order_txn_reference")
	_tdOrderInstruct.ExchangeType = field.NewString(tableName, "exchange_type")
	_tdOrderInstruct.MoneyType = field.NewString(tableName, "money_type")
	_tdOrderInstruct.StockCode = field.NewString(tableName, "stock_code")
	_tdOrderInstruct.StockType = field.NewString(tableName, "stock_type")
	_tdOrderInstruct.EntrustBs = field.NewInt64(tableName, "entrust_bs")
	_tdOrderInstruct.EntrustProp = field.NewString(tableName, "entrust_prop")
	_tdOrderInstruct.EntrustAmount = field.NewFloat64(tableName, "entrust_amount")
	_tdOrderInstruct.EntrustPrice = field.NewFloat64(tableName, "entrust_price")
	_tdOrderInstruct.EntrustBalance = field.NewFloat64(tableName, "entrust_balance")
	_tdOrderInstruct.FrozenPrice = field.NewFloat64(tableName, "frozen_price")
	_tdOrderInstruct.FrozenAmount = field.NewFloat64(tableName, "frozen_amount")
	_tdOrderInstruct.FrozenBalance = field.NewFloat64(tableName, "frozen_balance")
	_tdOrderInstruct.NewEntrustAmount = field.NewFloat64(tableName, "new_entrust_amount")
	_tdOrderInstruct.NewEntrustPrice = field.NewFloat64(tableName, "new_entrust_price")
	_tdOrderInstruct.DeltaAmount = field.NewFloat64(tableName, "delta_amount")
	_tdOrderInstruct.DeltaBalance = field.NewFloat64(tableName, "delta_balance")
	_tdOrderInstruct.RegisterAmount = field.NewFloat64(tableName, "register_amount")
	_tdOrderInstruct.WithdrawAmount = field.NewFloat64(tableName, "withdraw_amount")
	_tdOrderInstruct.FilledAmount = field.NewFloat64(tableName, "filled_amount")
	_tdOrderInstruct.FilledBalance = field.NewFloat64(tableName, "filled_balance")
	_tdOrderInstruct.OrigClordID = field.NewString(tableName, "orig_clord_id")
	_tdOrderInstruct.ExecNo = field.NewInt64(tableName, "exec_no")
	_tdOrderInstruct.ExecType = field.NewInt64(tableName, "exec_type")
	_tdOrderInstruct.ExecTime = field.NewInt64(tableName, "exec_time")
	_tdOrderInstruct.F11Clordid = field.NewString(tableName, "f11_clordid")
	_tdOrderInstruct.F14Cumqty = field.NewFloat64(tableName, "f14_cumqty")
	_tdOrderInstruct.F39Ordstatus = field.NewInt64(tableName, "f39_ordstatus")
	_tdOrderInstruct.F150Exectype = field.NewString(tableName, "f150_exectype")
	_tdOrderInstruct.F151Leavesqty = field.NewFloat64(tableName, "f151_leavesqty")
	_tdOrderInstruct.ErrorType = field.NewString(tableName, "error_type")
	_tdOrderInstruct.ErrorNo = field.NewInt64(tableName, "error_no")
	_tdOrderInstruct.ErrorMsg = field.NewString(tableName, "error_msg")

	_tdOrderInstruct.fillFieldMap()

	return _tdOrderInstruct
}

type tdOrderInstruct struct {
	tdOrderInstructDo tdOrderInstructDo

	ALL                 field.Asterisk
	ID                  field.Int64   // 自增id
	CreatedAt           field.Int64   // 创建时间
	UpdatedAt           field.Int64   // 更新时间
	SeatNo              field.String  // 席位编号 IB111
	ReportNo            field.String  // 申报编号
	ReportTime          field.Int64   // 申报时间,UTC 单位(秒)
	ReportAccount       field.String  // 报盘机申报子账号
	OrderInstructType   field.Int64   // 报盘指令类型,1=新订单报盘指令(New Order),2=改单盘指令(Order Replace),3=撤单盘指令(Order Cancel)
	OrderInstructStatus field.Int64   // 报盘指令执行状态,0=待审核(Pending Review),1=未执行(No Execute),2=待执行(Pending Execute),3=执行中(Executing),4=执行完毕(Executed)
	OrgID               field.String  // 机构编号
	ClientID            field.String  // 客户编号 1090000320
	FundAccount         field.String  // 资产账户 109000032001
	TradeDate           field.Int64   // 交易日期 20220228
	OrderTxnReference   field.String  // 记录号 2022022800US0000000001
	ExchangeType        field.String  // 交易所类别 HK/US
	MoneyType           field.String  // 币种类别
	StockCode           field.String  // 证券代码
	StockType           field.String  // 证券类别 [AC_STOCK_TYPE]0:Stock 1:Fund D:WRNT F:BWRT U:BOND i:Inline Warrant
	EntrustBs           field.Int64   // 买卖方向 1=买(Buy),2=卖(Sell)
	EntrustProp         field.String  // 委托属性 [TD_ORDER_PROPERTIES]ALO:At-auction Limit Order  AO:At-auction Order  ASO:Auto Stage Order  BC:Bulk Cancel  ELO:Enhanced Limit Order  LO:Limit Order  M:Manual Trade  MO:Market Order  O:Odd Lot Trade  OBC:OBO Bulk Cancel  ODD:Odd Lot Input  P:Pre Opening Trade  SLO:Special Limit Order  SODD:Special Odd Lot Order  V:Overseas Trade
	EntrustAmount       field.Float64 // 委托数量
	EntrustPrice        field.Float64 // 委托价格
	EntrustBalance      field.Float64 // 委托金额
	FrozenPrice         field.Float64 // 已冻结价格
	FrozenAmount        field.Float64 // 已冻结数量
	FrozenBalance       field.Float64 // 已冻结金额
	NewEntrustAmount    field.Float64 // 新委托数量/改单数量
	NewEntrustPrice     field.Float64 // 新委托价格/改单价格
	DeltaAmount         field.Float64 // 补冻数量
	DeltaBalance        field.Float64 // 补冻价格
	RegisterAmount      field.Float64 // 登记股数/剩余挂单数量
	WithdrawAmount      field.Float64 // 撤单数量,撤成数量
	FilledAmount        field.Float64 // 已成交数量
	FilledBalance       field.Float64 // 已成交金额
	OrigClordID         field.String  // 原始客户订单号--由报盘机生成 -- tag41组成因子
	ExecNo              field.Int64   // 执行回报编号
	ExecType            field.Int64   // 执行回报类型 1=下单已报执行回报(OrderAccepted)，2=下单拒绝执行回报(OrderRejected)，3=成交执行回报(Filled)，4=改单成功执行回报(OrderReplaced)，5=撤单成功执行回报(OrderCancelled)，6=改单/撤单拒绝执行回报(CancelReject)
	ExecTime            field.Int64   // 执行回报时间,UTC 单位(秒)
	F11Clordid          field.String  // 报盘订单ID
	F14Cumqty           field.Float64 // 累计成交数量
	F39Ordstatus        field.Int64   // 订单状态 1 = New，2=Rejected，3=Partially Filled，4=Filled，5=Cancelled
	F150Exectype        field.String  // 执行类型
	F151Leavesqty       field.Float64 // 剩余数量
	ErrorType           field.String  // 错误类型 a=交易前置错误 b=柜台内部错误 s=报盘机返回错误 e=交易所返回错误
	ErrorNo             field.Int64   // 错误代码 CxlRejReason
	ErrorMsg            field.String  // 错误提示 RejectText

	fieldMap map[string]field.Expr
}

func (t tdOrderInstruct) Table(newTableName string) *tdOrderInstruct {
	t.tdOrderInstructDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tdOrderInstruct) As(alias string) *tdOrderInstruct {
	t.tdOrderInstructDo.DO = *(t.tdOrderInstructDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tdOrderInstruct) updateTableName(table string) *tdOrderInstruct {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.CreatedAt = field.NewInt64(table, "created_at")
	t.UpdatedAt = field.NewInt64(table, "updated_at")
	t.SeatNo = field.NewString(table, "seat_no")
	t.ReportNo = field.NewString(table, "report_no")
	t.ReportTime = field.NewInt64(table, "report_time")
	t.ReportAccount = field.NewString(table, "report_account")
	t.OrderInstructType = field.NewInt64(table, "order_instruct_type")
	t.OrderInstructStatus = field.NewInt64(table, "order_instruct_status")
	t.OrgID = field.NewString(table, "org_id")
	t.ClientID = field.NewString(table, "client_id")
	t.FundAccount = field.NewString(table, "fund_account")
	t.TradeDate = field.NewInt64(table, "trade_date")
	t.OrderTxnReference = field.NewString(table, "order_txn_reference")
	t.ExchangeType = field.NewString(table, "exchange_type")
	t.MoneyType = field.NewString(table, "money_type")
	t.StockCode = field.NewString(table, "stock_code")
	t.StockType = field.NewString(table, "stock_type")
	t.EntrustBs = field.NewInt64(table, "entrust_bs")
	t.EntrustProp = field.NewString(table, "entrust_prop")
	t.EntrustAmount = field.NewFloat64(table, "entrust_amount")
	t.EntrustPrice = field.NewFloat64(table, "entrust_price")
	t.EntrustBalance = field.NewFloat64(table, "entrust_balance")
	t.FrozenPrice = field.NewFloat64(table, "frozen_price")
	t.FrozenAmount = field.NewFloat64(table, "frozen_amount")
	t.FrozenBalance = field.NewFloat64(table, "frozen_balance")
	t.NewEntrustAmount = field.NewFloat64(table, "new_entrust_amount")
	t.NewEntrustPrice = field.NewFloat64(table, "new_entrust_price")
	t.DeltaAmount = field.NewFloat64(table, "delta_amount")
	t.DeltaBalance = field.NewFloat64(table, "delta_balance")
	t.RegisterAmount = field.NewFloat64(table, "register_amount")
	t.WithdrawAmount = field.NewFloat64(table, "withdraw_amount")
	t.FilledAmount = field.NewFloat64(table, "filled_amount")
	t.FilledBalance = field.NewFloat64(table, "filled_balance")
	t.OrigClordID = field.NewString(table, "orig_clord_id")
	t.ExecNo = field.NewInt64(table, "exec_no")
	t.ExecType = field.NewInt64(table, "exec_type")
	t.ExecTime = field.NewInt64(table, "exec_time")
	t.F11Clordid = field.NewString(table, "f11_clordid")
	t.F14Cumqty = field.NewFloat64(table, "f14_cumqty")
	t.F39Ordstatus = field.NewInt64(table, "f39_ordstatus")
	t.F150Exectype = field.NewString(table, "f150_exectype")
	t.F151Leavesqty = field.NewFloat64(table, "f151_leavesqty")
	t.ErrorType = field.NewString(table, "error_type")
	t.ErrorNo = field.NewInt64(table, "error_no")
	t.ErrorMsg = field.NewString(table, "error_msg")

	t.fillFieldMap()

	return t
}

func (t *tdOrderInstruct) WithContext(ctx context.Context) ITdOrderInstructDo {
	return t.tdOrderInstructDo.WithContext(ctx)
}

func (t tdOrderInstruct) TableName() string { return t.tdOrderInstructDo.TableName() }

func (t tdOrderInstruct) Alias() string { return t.tdOrderInstructDo.Alias() }

func (t *tdOrderInstruct) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tdOrderInstruct) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 46)
	t.fieldMap["id"] = t.ID
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["seat_no"] = t.SeatNo
	t.fieldMap["report_no"] = t.ReportNo
	t.fieldMap["report_time"] = t.ReportTime
	t.fieldMap["report_account"] = t.ReportAccount
	t.fieldMap["order_instruct_type"] = t.OrderInstructType
	t.fieldMap["order_instruct_status"] = t.OrderInstructStatus
	t.fieldMap["org_id"] = t.OrgID
	t.fieldMap["client_id"] = t.ClientID
	t.fieldMap["fund_account"] = t.FundAccount
	t.fieldMap["trade_date"] = t.TradeDate
	t.fieldMap["order_txn_reference"] = t.OrderTxnReference
	t.fieldMap["exchange_type"] = t.ExchangeType
	t.fieldMap["money_type"] = t.MoneyType
	t.fieldMap["stock_code"] = t.StockCode
	t.fieldMap["stock_type"] = t.StockType
	t.fieldMap["entrust_bs"] = t.EntrustBs
	t.fieldMap["entrust_prop"] = t.EntrustProp
	t.fieldMap["entrust_amount"] = t.EntrustAmount
	t.fieldMap["entrust_price"] = t.EntrustPrice
	t.fieldMap["entrust_balance"] = t.EntrustBalance
	t.fieldMap["frozen_price"] = t.FrozenPrice
	t.fieldMap["frozen_amount"] = t.FrozenAmount
	t.fieldMap["frozen_balance"] = t.FrozenBalance
	t.fieldMap["new_entrust_amount"] = t.NewEntrustAmount
	t.fieldMap["new_entrust_price"] = t.NewEntrustPrice
	t.fieldMap["delta_amount"] = t.DeltaAmount
	t.fieldMap["delta_balance"] = t.DeltaBalance
	t.fieldMap["register_amount"] = t.RegisterAmount
	t.fieldMap["withdraw_amount"] = t.WithdrawAmount
	t.fieldMap["filled_amount"] = t.FilledAmount
	t.fieldMap["filled_balance"] = t.FilledBalance
	t.fieldMap["orig_clord_id"] = t.OrigClordID
	t.fieldMap["exec_no"] = t.ExecNo
	t.fieldMap["exec_type"] = t.ExecType
	t.fieldMap["exec_time"] = t.ExecTime
	t.fieldMap["f11_clordid"] = t.F11Clordid
	t.fieldMap["f14_cumqty"] = t.F14Cumqty
	t.fieldMap["f39_ordstatus"] = t.F39Ordstatus
	t.fieldMap["f150_exectype"] = t.F150Exectype
	t.fieldMap["f151_leavesqty"] = t.F151Leavesqty
	t.fieldMap["error_type"] = t.ErrorType
	t.fieldMap["error_no"] = t.ErrorNo
	t.fieldMap["error_msg"] = t.ErrorMsg
}

func (t tdOrderInstruct) clone(db *gorm.DB) tdOrderInstruct {
	t.tdOrderInstructDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tdOrderInstruct) replaceDB(db *gorm.DB) tdOrderInstruct {
	t.tdOrderInstructDo.ReplaceDB(db)
	return t
}

type tdOrderInstructDo struct{ gen.DO }

type ITdOrderInstructDo interface {
	gen.SubQuery
	Debug() ITdOrderInstructDo
	WithContext(ctx context.Context) ITdOrderInstructDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITdOrderInstructDo
	WriteDB() ITdOrderInstructDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITdOrderInstructDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITdOrderInstructDo
	Not(conds ...gen.Condition) ITdOrderInstructDo
	Or(conds ...gen.Condition) ITdOrderInstructDo
	Select(conds ...field.Expr) ITdOrderInstructDo
	Where(conds ...gen.Condition) ITdOrderInstructDo
	Order(conds ...field.Expr) ITdOrderInstructDo
	Distinct(cols ...field.Expr) ITdOrderInstructDo
	Omit(cols ...field.Expr) ITdOrderInstructDo
	Join(table schema.Tabler, on ...field.Expr) ITdOrderInstructDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITdOrderInstructDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITdOrderInstructDo
	Group(cols ...field.Expr) ITdOrderInstructDo
	Having(conds ...gen.Condition) ITdOrderInstructDo
	Limit(limit int) ITdOrderInstructDo
	Offset(offset int) ITdOrderInstructDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITdOrderInstructDo
	Unscoped() ITdOrderInstructDo
	Create(values ...*model.TdOrderInstruct) error
	CreateInBatches(values []*model.TdOrderInstruct, batchSize int) error
	Save(values ...*model.TdOrderInstruct) error
	First() (*model.TdOrderInstruct, error)
	Take() (*model.TdOrderInstruct, error)
	Last() (*model.TdOrderInstruct, error)
	Find() ([]*model.TdOrderInstruct, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TdOrderInstruct, err error)
	FindInBatches(result *[]*model.TdOrderInstruct, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TdOrderInstruct) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITdOrderInstructDo
	Assign(attrs ...field.AssignExpr) ITdOrderInstructDo
	Joins(fields ...field.RelationField) ITdOrderInstructDo
	Preload(fields ...field.RelationField) ITdOrderInstructDo
	FirstOrInit() (*model.TdOrderInstruct, error)
	FirstOrCreate() (*model.TdOrderInstruct, error)
	FindByPage(offset int, limit int) (result []*model.TdOrderInstruct, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITdOrderInstructDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tdOrderInstructDo) Debug() ITdOrderInstructDo {
	return t.withDO(t.DO.Debug())
}

func (t tdOrderInstructDo) WithContext(ctx context.Context) ITdOrderInstructDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tdOrderInstructDo) ReadDB() ITdOrderInstructDo {
	return t.Clauses(dbresolver.Read)
}

func (t tdOrderInstructDo) WriteDB() ITdOrderInstructDo {
	return t.Clauses(dbresolver.Write)
}

func (t tdOrderInstructDo) Session(config *gorm.Session) ITdOrderInstructDo {
	return t.withDO(t.DO.Session(config))
}

func (t tdOrderInstructDo) Clauses(conds ...clause.Expression) ITdOrderInstructDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tdOrderInstructDo) Returning(value interface{}, columns ...string) ITdOrderInstructDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tdOrderInstructDo) Not(conds ...gen.Condition) ITdOrderInstructDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tdOrderInstructDo) Or(conds ...gen.Condition) ITdOrderInstructDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tdOrderInstructDo) Select(conds ...field.Expr) ITdOrderInstructDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tdOrderInstructDo) Where(conds ...gen.Condition) ITdOrderInstructDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tdOrderInstructDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) ITdOrderInstructDo {
	return t.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (t tdOrderInstructDo) Order(conds ...field.Expr) ITdOrderInstructDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tdOrderInstructDo) Distinct(cols ...field.Expr) ITdOrderInstructDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tdOrderInstructDo) Omit(cols ...field.Expr) ITdOrderInstructDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tdOrderInstructDo) Join(table schema.Tabler, on ...field.Expr) ITdOrderInstructDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tdOrderInstructDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITdOrderInstructDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tdOrderInstructDo) RightJoin(table schema.Tabler, on ...field.Expr) ITdOrderInstructDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tdOrderInstructDo) Group(cols ...field.Expr) ITdOrderInstructDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tdOrderInstructDo) Having(conds ...gen.Condition) ITdOrderInstructDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tdOrderInstructDo) Limit(limit int) ITdOrderInstructDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tdOrderInstructDo) Offset(offset int) ITdOrderInstructDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tdOrderInstructDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITdOrderInstructDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tdOrderInstructDo) Unscoped() ITdOrderInstructDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tdOrderInstructDo) Create(values ...*model.TdOrderInstruct) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tdOrderInstructDo) CreateInBatches(values []*model.TdOrderInstruct, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tdOrderInstructDo) Save(values ...*model.TdOrderInstruct) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tdOrderInstructDo) First() (*model.TdOrderInstruct, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TdOrderInstruct), nil
	}
}

func (t tdOrderInstructDo) Take() (*model.TdOrderInstruct, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TdOrderInstruct), nil
	}
}

func (t tdOrderInstructDo) Last() (*model.TdOrderInstruct, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TdOrderInstruct), nil
	}
}

func (t tdOrderInstructDo) Find() ([]*model.TdOrderInstruct, error) {
	result, err := t.DO.Find()
	return result.([]*model.TdOrderInstruct), err
}

func (t tdOrderInstructDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TdOrderInstruct, err error) {
	buf := make([]*model.TdOrderInstruct, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tdOrderInstructDo) FindInBatches(result *[]*model.TdOrderInstruct, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tdOrderInstructDo) Attrs(attrs ...field.AssignExpr) ITdOrderInstructDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tdOrderInstructDo) Assign(attrs ...field.AssignExpr) ITdOrderInstructDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tdOrderInstructDo) Joins(fields ...field.RelationField) ITdOrderInstructDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tdOrderInstructDo) Preload(fields ...field.RelationField) ITdOrderInstructDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tdOrderInstructDo) FirstOrInit() (*model.TdOrderInstruct, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TdOrderInstruct), nil
	}
}

func (t tdOrderInstructDo) FirstOrCreate() (*model.TdOrderInstruct, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TdOrderInstruct), nil
	}
}

func (t tdOrderInstructDo) FindByPage(offset int, limit int) (result []*model.TdOrderInstruct, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tdOrderInstructDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tdOrderInstructDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tdOrderInstructDo) Delete(models ...*model.TdOrderInstruct) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tdOrderInstructDo) withDO(do gen.Dao) *tdOrderInstructDo {
	t.DO = *do.(*gen.DO)
	return t
}
