// Code generated by goctl. DO NOT EDIT.
// Source: rpcdemo.proto

package server

import (
	"context"

	"go-lib/frame/go-zero/rpcdemo/internal/logic"
	"go-lib/frame/go-zero/rpcdemo/internal/svc"
	"go-lib/frame/go-zero/rpcdemo/rpcdemo"
)

type RpcDemoServer struct {
	svcCtx *svc.ServiceContext
	rpcdemo.UnimplementedRpcDemoServer
}

func NewRpcDemoServer(svcCtx *svc.ServiceContext) *RpcDemoServer {
	return &RpcDemoServer{
		svcCtx: svcCtx,
	}
}

func (s *RpcDemoServer) Ping(ctx context.Context, in *rpcdemo.Request) (*rpcdemo.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
