// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: p1.proto

package p1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ResolverService_Resolver_FullMethodName = "/p1.ResolverService/resolver"
)

// ResolverServiceClient is the client API for ResolverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResolverServiceClient interface {
	// 方法
	Resolver(ctx context.Context, in *P10086, opts ...grpc.CallOption) (*P10086, error)
}

type resolverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResolverServiceClient(cc grpc.ClientConnInterface) ResolverServiceClient {
	return &resolverServiceClient{cc}
}

func (c *resolverServiceClient) Resolver(ctx context.Context, in *P10086, opts ...grpc.CallOption) (*P10086, error) {
	out := new(P10086)
	err := c.cc.Invoke(ctx, ResolverService_Resolver_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResolverServiceServer is the server API for ResolverService service.
// All implementations must embed UnimplementedResolverServiceServer
// for forward compatibility
type ResolverServiceServer interface {
	// 方法
	Resolver(context.Context, *P10086) (*P10086, error)
	mustEmbedUnimplementedResolverServiceServer()
}

// UnimplementedResolverServiceServer must be embedded to have forward compatible implementations.
type UnimplementedResolverServiceServer struct {
}

func (UnimplementedResolverServiceServer) Resolver(context.Context, *P10086) (*P10086, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resolver not implemented")
}
func (UnimplementedResolverServiceServer) mustEmbedUnimplementedResolverServiceServer() {}

// UnsafeResolverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResolverServiceServer will
// result in compilation errors.
type UnsafeResolverServiceServer interface {
	mustEmbedUnimplementedResolverServiceServer()
}

func RegisterResolverServiceServer(s grpc.ServiceRegistrar, srv ResolverServiceServer) {
	s.RegisterService(&ResolverService_ServiceDesc, srv)
}

func _ResolverService_Resolver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(P10086)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolverServiceServer).Resolver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResolverService_Resolver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolverServiceServer).Resolver(ctx, req.(*P10086))
	}
	return interceptor(ctx, in, info, handler)
}

// ResolverService_ServiceDesc is the grpc.ServiceDesc for ResolverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResolverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "p1.ResolverService",
	HandlerType: (*ResolverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "resolver",
			Handler:    _ResolverService_Resolver_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "p1.proto",
}
