apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
      name: http
      nodePort: 30001

  selector:
    app: hello-world