// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type GetUserInfoByNameReq struct {
	Name string `json:"name" validate:"required"`
}
