// Code generated by goctl. DO NOT EDIT.
// Source: rpcdemo.proto

package rpc_demo_client

import (
	"context"

	"go-lib/frame/go-zero/rpcdemo/rpcdemo"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = rpcdemo.Request
	Response = rpcdemo.Response

	RpcDemo interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultRpcDemo struct {
		cli zrpc.Client
	}
)

func NewRpcDemo(cli zrpc.Client) RpcDemo {
	return &defaultRpcDemo{
		cli: cli,
	}
}

func (m *defaultRpcDemo) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := rpcdemo.NewRpcDemoClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
