
// Code generated by tool. DO NOT EDIT.
// Code generated by tool. DO NOT EDIT.
// Code generated by tool. DO NOT EDIT.

package main

import (
	"google.golang.org/grpc/status"
)

var (
	UnAuthorized    =   status.Error(UnAuthorizedCode,"403未授权")
	NotFound        =   status.Error(NotFoundCode,"404未找到")
)
/*

403     403未授权    
404     404未找到    


*/
