// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: mutl_message.proto

package mult

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ping string `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mutl_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_mutl_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_mutl_message_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type UserClassListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserClassListReq) Reset() {
	*x = UserClassListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mutl_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserClassListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserClassListReq) ProtoMessage() {}

func (x *UserClassListReq) ProtoReflect() protoreflect.Message {
	mi := &file_mutl_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserClassListReq.ProtoReflect.Descriptor instead.
func (*UserClassListReq) Descriptor() ([]byte, []int) {
	return file_mutl_message_proto_rawDescGZIP(), []int{1}
}

type UserClassListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserClassListResp) Reset() {
	*x = UserClassListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mutl_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserClassListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserClassListResp) ProtoMessage() {}

func (x *UserClassListResp) ProtoReflect() protoreflect.Message {
	mi := &file_mutl_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserClassListResp.ProtoReflect.Descriptor instead.
func (*UserClassListResp) Descriptor() ([]byte, []int) {
	return file_mutl_message_proto_rawDescGZIP(), []int{2}
}

type UserClassUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserClassUpdateReq) Reset() {
	*x = UserClassUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mutl_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserClassUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserClassUpdateReq) ProtoMessage() {}

func (x *UserClassUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_mutl_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserClassUpdateReq.ProtoReflect.Descriptor instead.
func (*UserClassUpdateReq) Descriptor() ([]byte, []int) {
	return file_mutl_message_proto_rawDescGZIP(), []int{3}
}

type UserClassUpdateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserClassUpdateResp) Reset() {
	*x = UserClassUpdateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mutl_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserClassUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserClassUpdateResp) ProtoMessage() {}

func (x *UserClassUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_mutl_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserClassUpdateResp.ProtoReflect.Descriptor instead.
func (*UserClassUpdateResp) Descriptor() ([]byte, []int) {
	return file_mutl_message_proto_rawDescGZIP(), []int{4}
}

type UserClassInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserClassInfoReq) Reset() {
	*x = UserClassInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mutl_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserClassInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserClassInfoReq) ProtoMessage() {}

func (x *UserClassInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_mutl_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserClassInfoReq.ProtoReflect.Descriptor instead.
func (*UserClassInfoReq) Descriptor() ([]byte, []int) {
	return file_mutl_message_proto_rawDescGZIP(), []int{5}
}

type UserClassInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserClassInfoResp) Reset() {
	*x = UserClassInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mutl_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserClassInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserClassInfoResp) ProtoMessage() {}

func (x *UserClassInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_mutl_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserClassInfoResp.ProtoReflect.Descriptor instead.
func (*UserClassInfoResp) Descriptor() ([]byte, []int) {
	return file_mutl_message_proto_rawDescGZIP(), []int{6}
}

type UserClassAddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserClassAddReq) Reset() {
	*x = UserClassAddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mutl_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserClassAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserClassAddReq) ProtoMessage() {}

func (x *UserClassAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_mutl_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserClassAddReq.ProtoReflect.Descriptor instead.
func (*UserClassAddReq) Descriptor() ([]byte, []int) {
	return file_mutl_message_proto_rawDescGZIP(), []int{7}
}

type UserClassAddResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserClassAddResp) Reset() {
	*x = UserClassAddResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mutl_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserClassAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserClassAddResp) ProtoMessage() {}

func (x *UserClassAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_mutl_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserClassAddResp.ProtoReflect.Descriptor instead.
func (*UserClassAddResp) Descriptor() ([]byte, []int) {
	return file_mutl_message_proto_rawDescGZIP(), []int{8}
}

type UserClassDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserClassDeleteReq) Reset() {
	*x = UserClassDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mutl_message_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserClassDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserClassDeleteReq) ProtoMessage() {}

func (x *UserClassDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_mutl_message_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserClassDeleteReq.ProtoReflect.Descriptor instead.
func (*UserClassDeleteReq) Descriptor() ([]byte, []int) {
	return file_mutl_message_proto_rawDescGZIP(), []int{9}
}

type UserClassDeleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserClassDeleteResp) Reset() {
	*x = UserClassDeleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mutl_message_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserClassDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserClassDeleteResp) ProtoMessage() {}

func (x *UserClassDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_mutl_message_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserClassDeleteResp.ProtoReflect.Descriptor instead.
func (*UserClassDeleteResp) Descriptor() ([]byte, []int) {
	return file_mutl_message_proto_rawDescGZIP(), []int{10}
}

var File_mutl_message_proto protoreflect.FileDescriptor

var file_mutl_message_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x75, 0x74, 0x6c, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x75, 0x6c, 0x74, 0x22, 0x1d, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x22, 0x12, 0x0a, 0x10, 0x55, 0x73, 0x65,
	0x72, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x13, 0x0a,
	0x11, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x14, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x22, 0x15, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x12, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x22, 0x13, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x22, 0x11, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x22, 0x12, 0x0a, 0x10, 0x55,
	0x73, 0x65, 0x72, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x14, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x22, 0x15, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x08, 0x5a, 0x06,
	0x2e, 0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mutl_message_proto_rawDescOnce sync.Once
	file_mutl_message_proto_rawDescData = file_mutl_message_proto_rawDesc
)

func file_mutl_message_proto_rawDescGZIP() []byte {
	file_mutl_message_proto_rawDescOnce.Do(func() {
		file_mutl_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_mutl_message_proto_rawDescData)
	})
	return file_mutl_message_proto_rawDescData
}

var file_mutl_message_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_mutl_message_proto_goTypes = []interface{}{
	(*Request)(nil),             // 0: mult.Request
	(*UserClassListReq)(nil),    // 1: mult.UserClassListReq
	(*UserClassListResp)(nil),   // 2: mult.UserClassListResp
	(*UserClassUpdateReq)(nil),  // 3: mult.UserClassUpdateReq
	(*UserClassUpdateResp)(nil), // 4: mult.UserClassUpdateResp
	(*UserClassInfoReq)(nil),    // 5: mult.UserClassInfoReq
	(*UserClassInfoResp)(nil),   // 6: mult.UserClassInfoResp
	(*UserClassAddReq)(nil),     // 7: mult.UserClassAddReq
	(*UserClassAddResp)(nil),    // 8: mult.UserClassAddResp
	(*UserClassDeleteReq)(nil),  // 9: mult.UserClassDeleteReq
	(*UserClassDeleteResp)(nil), // 10: mult.UserClassDeleteResp
}
var file_mutl_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mutl_message_proto_init() }
func file_mutl_message_proto_init() {
	if File_mutl_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mutl_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mutl_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserClassListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mutl_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserClassListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mutl_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserClassUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mutl_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserClassUpdateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mutl_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserClassInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mutl_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserClassInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mutl_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserClassAddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mutl_message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserClassAddResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mutl_message_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserClassDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mutl_message_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserClassDeleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mutl_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mutl_message_proto_goTypes,
		DependencyIndexes: file_mutl_message_proto_depIdxs,
		MessageInfos:      file_mutl_message_proto_msgTypes,
	}.Build()
	File_mutl_message_proto = out.File
	file_mutl_message_proto_rawDesc = nil
	file_mutl_message_proto_goTypes = nil
	file_mutl_message_proto_depIdxs = nil
}
