// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: p2.proto

package pb2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	p1 "protobuf/import/p1"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type P2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Test *p1.P1 `protobuf:"bytes,2,opt,name=test,proto3" json:"test,omitempty"`
	Age  int32  `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *P2) Reset() {
	*x = P2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *P2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2) ProtoMessage() {}

func (x *P2) ProtoReflect() protoreflect.Message {
	mi := &file_p2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2.ProtoReflect.Descriptor instead.
func (*P2) Descriptor() ([]byte, []int) {
	return file_p2_proto_rawDescGZIP(), []int{0}
}

func (x *P2) GetTest() *p1.P1 {
	if x != nil {
		return x.Test
	}
	return nil
}

func (x *P2) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

var File_p2_proto protoreflect.FileDescriptor

var file_p2_proto_rawDesc = []byte{
	0x0a, 0x08, 0x70, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x32, 0x1a, 0x08,
	0x70, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x02, 0x50, 0x32, 0x12, 0x1a,
	0x0a, 0x04, 0x74, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x70,
	0x31, 0x2e, 0x50, 0x31, 0x52, 0x04, 0x74, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x42, 0x07, 0x5a, 0x05,
	0x2e, 0x2f, 0x70, 0x62, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_p2_proto_rawDescOnce sync.Once
	file_p2_proto_rawDescData = file_p2_proto_rawDesc
)

func file_p2_proto_rawDescGZIP() []byte {
	file_p2_proto_rawDescOnce.Do(func() {
		file_p2_proto_rawDescData = protoimpl.X.CompressGZIP(file_p2_proto_rawDescData)
	})
	return file_p2_proto_rawDescData
}

var file_p2_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_p2_proto_goTypes = []interface{}{
	(*P2)(nil),    // 0: p2.P2
	(*p1.P1)(nil), // 1: p1.P1
}
var file_p2_proto_depIdxs = []int32{
	1, // 0: p2.P2.test:type_name -> p1.P1
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_p2_proto_init() }
func file_p2_proto_init() {
	if File_p2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_p2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*P2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_p2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_p2_proto_goTypes,
		DependencyIndexes: file_p2_proto_depIdxs,
		MessageInfos:      file_p2_proto_msgTypes,
	}.Build()
	File_p2_proto = out.File
	file_p2_proto_rawDesc = nil
	file_p2_proto_goTypes = nil
	file_p2_proto_depIdxs = nil
}
