100005 = "Record Not Found"
110000 = "internal error"
120000 = "internal error"
130000 = "internal error"
131000 = "internal error"
132000 = "internal error"
135000 = "internal error"
136000 = "internal error"
140000 = "AuthFailed"
150000 = "Timeout"
170000 = "ParamValidateFailed"
171000 = "HeadValidateFailed"
200001 = "UserNotFound"
200002 = "AmountInsufficient"
200003 = "Token Invalid"
200004 = "Token Expire"
200005 = "The account or password is incorrect"
300001 = "order not found"
300002 = "order has filled"
300003 = "market order can not cancel"
300004 = "not bids"
300005 = "no asks"
999999 = "internal error"