gen:
	gentool.exe --dsn="root:root@tcp(192.168.254.99:3306)/test?charset=utf8mb4&parseTime=True&loc=Local" --db=mysql --tables=t_user --tablePrefix="t_" -outPath=dao/query -fieldMap="decimal:string;tinyint:int32;"
