apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: busybox
      command: ["sh", "-c", "while true; do echo $(date) >> /mnt/data/datetime.log; sleep 5; done"]
      volumeMounts:
        - mountPath: /mnt/data
          name: my-storage
  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: my-pvc
