// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTdStkcode = "td_stkcode"

// TdStkcode mapped from table <td_stkcode>
type TdStkcode struct {
	ID                 int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增id" json:"id"`
	CreatedAt          int64  `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`
	UpdatedAt          int64  `gorm:"column:updated_at;not null;comment:更新时间" json:"updated_at"`
	ExchangeType       string `gorm:"column:exchange_type;not null;default:' ';comment:交易市场" json:"exchange_type"`
	MoneyType          string `gorm:"column:money_type;not null;default:' ';comment:币种类别" json:"money_type"`
	StockCode          string `gorm:"column:stock_code;not null;default:' ';comment:证券代码" json:"stock_code"`
	StockName          string `gorm:"column:stock_name;not null;default:' ';comment:证券名称" json:"stock_name"`
	StockFullname      string `gorm:"column:stock_fullname;not null;default:' ';comment:证券全称" json:"stock_fullname"`
	MarginType         int32  `gorm:"column:margin_type;not null;comment:融资类型, 1-融资额度 2-融资比例" json:"margin_type"`
	MarginValue        string `gorm:"column:margin_value;not null;default:0.0000;comment:融资额度" json:"margin_value"`
	Financingrate      string `gorm:"column:financingrate;not null;comment:融资比例% 50.20%" json:"financingrate"`
	MaxMarginValue     string `gorm:"column:max_margin_value;not null;default:0.0000;comment:融资上限额度" json:"max_margin_value"`
	QtyDecLen          int32  `gorm:"column:qty_dec_len;not null;comment:数量小数位数" json:"qty_dec_len"`
	PriDecLen          int32  `gorm:"column:pri_dec_len;not null;comment:价格小数位数" json:"pri_dec_len"`
	LotSize            int32  `gorm:"column:lot_size;comment:每手股数" json:"lot_size"`
	SpreadTableCode    int32  `gorm:"column:spread_table_code;default:1;comment:对应价差表编码  值为1:A,3:B,4:C,5:D" json:"spread_table_code"`
	OpenPrice          string `gorm:"column:open_price;not null;default:0.0000;comment:开盘价" json:"open_price"`
	PreviousClosePrice string `gorm:"column:previous_close_price;not null;default:0.0000;comment:昨收盘价" json:"previous_close_price"`
	TradeFlag          int32  `gorm:"column:trade_flag;not null;comment:交易标志 0-初始化 1-允许交易 2-不允许交易" json:"trade_flag"`
	Status             int32  `gorm:"column:status;not null;comment:生效标志 0-初始化 1-生效 2-不生效" json:"status"`
}

// TableName TdStkcode's table name
func (*TdStkcode) TableName() string {
	return TableNameTdStkcode
}
